//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Login.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_banned
    {
        public long id { get; set; }
        public long bandate { get; set; }
        public long unbandate { get; set; }
        public string bannedby { get; set; }
        public string banreason { get; set; }
        public short active { get; set; }
    }
}
