//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Login.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoginDatabase : DbContext
    {
        public LoginDatabase()
            : base("name=LoginDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<account_banned> account_banned { get; set; }
        public virtual DbSet<ip_banned> ip_banned { get; set; }
        public virtual DbSet<realmcharacter> realmcharacters { get; set; }
        public virtual DbSet<realmlist> realmlists { get; set; }
        public virtual DbSet<uptime> uptimes { get; set; }
    }
}
