//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Login.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class realmlist
    {
        public long id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public int port { get; set; }
        public byte icon { get; set; }
        public byte realmflags { get; set; }
        public byte timezone { get; set; }
        public byte allowedSecurityLevel { get; set; }
        public string realmbuilds { get; set; }
    }
}
