//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Login.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class uptime
    {
        public long realmid { get; set; }
        public decimal starttime { get; set; }
        public string startstring { get; set; }
        public decimal uptime1 { get; set; }
        public int maxplayers { get; set; }
    }
}
