//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class auction
    {
        public long id { get; set; }
        public long houseid { get; set; }
        public long itemguid { get; set; }
        public long item_template { get; set; }
        public long item_count { get; set; }
        public int item_randompropertyid { get; set; }
        public long itemowner { get; set; }
        public int buyoutprice { get; set; }
        public decimal time { get; set; }
        public long buyguid { get; set; }
        public int lastbid { get; set; }
        public int startbid { get; set; }
        public int deposit { get; set; }
    }
}
