//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_pet
    {
        public long id { get; set; }
        public long entry { get; set; }
        public long owner { get; set; }
        public Nullable<long> modelid { get; set; }
        public long CreatedBySpell { get; set; }
        public byte PetType { get; set; }
        public long level { get; set; }
        public long exp { get; set; }
        public bool Reactstate { get; set; }
        public int loyaltypoints { get; set; }
        public long loyalty { get; set; }
        public int trainpoint { get; set; }
        public string name { get; set; }
        public bool renamed { get; set; }
        public long slot { get; set; }
        public long curhealth { get; set; }
        public long curmana { get; set; }
        public long curhappiness { get; set; }
        public decimal savetime { get; set; }
        public long resettalents_cost { get; set; }
        public decimal resettalents_time { get; set; }
        public string abdata { get; set; }
        public string teachspelldata { get; set; }
    }
}
