//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_battleground_data
    {
        public long guid { get; set; }
        public long instance_id { get; set; }
        public long team { get; set; }
        public float join_x { get; set; }
        public float join_y { get; set; }
        public float join_z { get; set; }
        public float join_o { get; set; }
        public int join_map { get; set; }
    }
}
