//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_stats
    {
        public long guid { get; set; }
        public long maxhealth { get; set; }
        public long maxpower1 { get; set; }
        public long maxpower2 { get; set; }
        public long maxpower3 { get; set; }
        public long maxpower4 { get; set; }
        public long maxpower5 { get; set; }
        public long maxpower6 { get; set; }
        public long maxpower7 { get; set; }
        public long strength { get; set; }
        public long agility { get; set; }
        public long stamina { get; set; }
        public long intellect { get; set; }
        public long spirit { get; set; }
        public long armor { get; set; }
        public long resHoly { get; set; }
        public long resFire { get; set; }
        public long resNature { get; set; }
        public long resFrost { get; set; }
        public long resShadow { get; set; }
        public long resArcane { get; set; }
        public long attackPower { get; set; }
        public long rangedAttackPower { get; set; }
    }
}
