//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_queststatus
    {
        public long guid { get; set; }
        public long quest { get; set; }
        public long status { get; set; }
        public bool rewarded { get; set; }
        public bool explored { get; set; }
        public decimal timer { get; set; }
        public long mobcount1 { get; set; }
        public long mobcount2 { get; set; }
        public long mobcount3 { get; set; }
        public long mobcount4 { get; set; }
        public long itemcount1 { get; set; }
        public long itemcount2 { get; set; }
        public long itemcount3 { get; set; }
        public long itemcount4 { get; set; }
    }
}
