//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_honor_cp
    {
        public long guid { get; set; }
        public byte victim_type { get; set; }
        public long victim { get; set; }
        public float honor { get; set; }
        public long date { get; set; }
        public byte type { get; set; }
    }
}
