//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_tutorial
    {
        public long account { get; set; }
        public long tut0 { get; set; }
        public long tut1 { get; set; }
        public long tut2 { get; set; }
        public long tut3 { get; set; }
        public long tut4 { get; set; }
        public long tut5 { get; set; }
        public long tut6 { get; set; }
        public long tut7 { get; set; }
    }
}
