//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public long groupId { get; set; }
        public long leaderGuid { get; set; }
        public long mainTank { get; set; }
        public long mainAssistant { get; set; }
        public byte lootMethod { get; set; }
        public long looterGuid { get; set; }
        public byte lootThreshold { get; set; }
        public long icon1 { get; set; }
        public long icon2 { get; set; }
        public long icon3 { get; set; }
        public long icon4 { get; set; }
        public long icon5 { get; set; }
        public long icon6 { get; set; }
        public long icon7 { get; set; }
        public long icon8 { get; set; }
        public bool isRaid { get; set; }
    }
}
