//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_member
    {
        public long groupId { get; set; }
        public long memberGuid { get; set; }
        public byte assistant { get; set; }
        public int subgroup { get; set; }
    }
}
