//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild
    {
        public long guildid { get; set; }
        public string name { get; set; }
        public long leaderguid { get; set; }
        public int EmblemStyle { get; set; }
        public int EmblemColor { get; set; }
        public int BorderStyle { get; set; }
        public int BorderColor { get; set; }
        public int BackgroundColor { get; set; }
        public string info { get; set; }
        public string motd { get; set; }
        public decimal createdate { get; set; }
    }
}
