//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_member
    {
        public long guildid { get; set; }
        public long guid { get; set; }
        public byte rank { get; set; }
        public string pnote { get; set; }
        public string offnote { get; set; }
    }
}
