//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_loot
    {
        public long guid { get; set; }
        public long owner_guid { get; set; }
        public long itemid { get; set; }
        public long amount { get; set; }
        public int property { get; set; }
    }
}
