//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail
    {
        public long id { get; set; }
        public byte messageType { get; set; }
        public short stationery { get; set; }
        public int mailTemplateId { get; set; }
        public long sender { get; set; }
        public long receiver { get; set; }
        public string subject { get; set; }
        public long itemTextId { get; set; }
        public byte has_items { get; set; }
        public long expire_time { get; set; }
        public long deliver_time { get; set; }
        public long money { get; set; }
        public long cod { get; set; }
        public byte @checked { get; set; }
    }
}
