//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Character.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet_aura
    {
        public long guid { get; set; }
        public decimal caster_guid { get; set; }
        public long item_guid { get; set; }
        public long spell { get; set; }
        public long stackcount { get; set; }
        public long remaincharges { get; set; }
        public int basepoints0 { get; set; }
        public int basepoints1 { get; set; }
        public int basepoints2 { get; set; }
        public long periodictime0 { get; set; }
        public long periodictime1 { get; set; }
        public long periodictime2 { get; set; }
        public int maxduration { get; set; }
        public int remaintime { get; set; }
        public long effIndexMask { get; set; }
    }
}
