namespace Vanilla.World.Components.Character.Constants
{
    public enum InventorySlotID : byte
    {
        None,
        Head,
        Neck,
        Shoulders,
        Shirt,
        Vest,
        Waist,
        Legs,
        Feet,
        Wrist,
        Hands,
        Ring,
        Trinket,
        Onehand,
        Shield,
        Bow,
        Back,
        Twohand,
        Bag,
        Tabbard,
        Robe,
        Mainhand,
        Offhand,
        Held,
        Ammo,
        Thrown,
        Ranged,
        Ranged2,
        Relic
    }
}
