using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Milkshake.Tools.DBC.Tables
{
    public class SpellEntry
    {
        public int ID { get; set; } 
        public int School { get; set; } 
        public int Category { get; set; } 
        public int castUI { get; set; } 
        public int Dispel { get; set; } 
        public int Mechanic { get; set; } 
        public int Attributes { get; set; } 
        public int AttributesEx { get; set; } 
        public int AttributesEx2 { get; set; } 
        public int AttributesEx3 { get; set; } 
        public int AttributesEx4 { get; set; } 
        public int Stances { get; set; } 
        public int StancesNot { get; set; } 
        public int Targets { get; set; } 
        public int TargetCreatureType { get; set; } 
        public int RequiresSpellFocus { get; set; } 
        public int CasterAuraState { get; set; } 
        public int TargetAuraState { get; set; } 
        public int CastingTimeIndex { get; set; } 
        public int RecoveryTime { get; set; } 
        public int CategoryRecoveryTime { get; set; } 
        public int InterruptFlags { get; set; } 
        public int AuraInterruptFlags { get; set; } 
        public int ChannelInterruptFlags { get; set; } 
        public int procFlags { get; set; } 
        public int procChance { get; set; } 
        public int procCharges { get; set; } 
        public int maxLevel { get; set; } 
        public int baseLevel { get; set; } 
        public int spellLevel { get; set; } 
        public int DurationIndex { get; set; } 
        public int powerType { get; set; } 
        public int manaCost { get; set; } 
        public int manaCostPerlevel { get; set; } 
        public int manaPerSecond { get; set; } 
        public int manaPerSecondPerLevel { get; set; } 
        public int rangeIndex { get; set; } 
        public float speed { get; set; } 
        public int modalNextSpell { get; set; }
        public string Name { get { return SpellName1; } }
        public int StackAmount { get; set; } 
        public int Totem1 { get; set; }
        public int Totem2 { get; set; } 
        public int Reagent1 { get; set; } 
        public int Reagent2 { get; set; } 
        public int Reagent3 { get; set; } 
        public int Reagent4 { get; set; } 
        public int Reagent5 { get; set; } 
        public int Reagent6 { get; set; } 
        public int Reagent7 { get; set; } 
        public int Reagent8 { get; set; }
        public int ReagentCount1 { get; set; }
        public int ReagentCount2 { get; set; } 
        public int ReagentCount3 { get; set; } 
        public int ReagentCount4 { get; set; } 
        public int ReagentCount5 { get; set; } 
        public int ReagentCount6 { get; set; } 
        public int ReagentCount7 { get; set; } 
        public int ReagentCount8 { get; set; } 
        public int EquippedItemClass { get; set; } 
        public int EquippedItemSubClassMask { get; set; } 
        public int EquippedItemInventoryTypeMask { get; set; } 
        public int Effect1 { get; set; } 
        public int Effect2 { get; set; } 
        public int Effect3 { get; set; } 
        public int EffectDieSides1 { get; set; }
        public int EffectDieSides2 { get; set; } 
        public int EffectDieSides3 { get; set; } 
        public int EffectBaseDice1 { get; set; } 
        public int EffectBaseDice2 { get; set; } 
        public int EffectBaseDice3 { get; set; }  
        public float EffectDicePerLevel1 { get; set; }
        public float EffectDicePerLevel2 { get; set; } 
        public float EffectDicePerLevel3 { get; set; } 
        public float EffectRealPointsPerLevel1 { get; set; } 
        public float EffectRealPointsPerLevel2 { get; set; } 
        public float EffectRealPointsPerLevel3 { get; set; } 
        public int EffectBasePoints1 { get; set; } 
        public int EffectBasePoints2 { get; set; } 
        public int EffectBasePoints3 { get; set; } 
        public int EffectMechanic1 { get; set; }
        public int EffectMechanic2 { get; set; } 
        public int EffectMechanic3 { get; set; } 
        public int EffectImplicitTargetA1 { get; set; } 
        public int EffectImplicitTargetA2 { get; set; } 
        public int EffectImplicitTargetA3 { get; set; } 
        public int EffectImplicitTargetB1{ get; set; } 
        public int EffectImplicitTargetB2{ get; set; } 
        public int EffectImplicitTargetB3{ get; set; } 
        public int EffectRadiusIndex1 { get; set; } 
        public int EffectRadiusIndex2 { get; set; } 
        public int EffectRadiusIndex3 { get; set; } 
        public int EffectApplyAuraName1 { get; set; } 
        public int EffectApplyAuraName2 { get; set; } 
        public int EffectApplyAuraName3 { get; set; } 
        public int EffectAmplitude1 { get; set; } 
        public int EffectAmplitude2 { get; set; } 
        public int EffectAmplitude3 { get; set; } 
        public float EffectMultipleValue1 { get; set; } 
        public float EffectMultipleValue2 { get; set; } 
        public float EffectMultipleValue3 { get; set; } 
        public int EffectChainTarget1 { get; set; } 
        public int EffectChainTarget2 { get; set; } 
        public int EffectChainTarget3 { get; set; } 
        public int EffectItemType1 { get; set; } 
        public int EffectItemType2 { get; set; } 
        public int EffectItemType3 { get; set; } 
        public int EffectMiscValue1 { get; set; } 
        public int EffectMiscValue2 { get; set; } 
        public int EffectMiscValue3 { get; set; } 
        public int EffectTriggerSpell1 { get; set; } 
        public int EffectTriggerSpell2 { get; set; } 
        public int EffectTriggerSpell3 { get; set; } 
        public float EffectPointsPerComboPoint1 { get; set; } 
        public float EffectPointsPerComboPoint2 { get; set; } 
        public float EffectPointsPerComboPoint3 { get; set; } 
        public int SpellVisual { get; set; } 
        public int SpellVisual2 { get; set; } 
        public int SpellIconID { get; set; } 
        public int activeIconID { get; set; } 
        public int spellPriority { get; set; } 
        public string SpellName1 { get; set; }
        public string SpellName2 { get; set; } 
        public string SpellName3 { get; set; } 
        public string SpellName4 { get; set; } 
        public string SpellName5 { get; set; } 
        public string SpellName6 { get; set; } 
        public string SpellName7 { get; set; } 
        public string SpellName8 { get; set; } 
        public int SpellNameFlag { get; set; } 
        public string Rank1 { get; set; } 
        public string Rank2 { get; set; } 
        public string Rank3 { get; set; } 
        public string Rank4 { get; set; } 
        public string Rank5 { get; set; } 
        public string Rank6 { get; set; } 
        public string Rank7 { get; set; } 
        public string Rank8 { get; set; } 
        public int RankFlags { get; set; } 
        public string Description1 { get; set; }
        public string Description2 { get; set; } 
        public string Description3 { get; set; } 
        public string Description4 { get; set; } 
        public string Description5 { get; set; } 
        public string Description6 { get; set; } 
        public string Description7 { get; set; } 
        public string Description8 { get; set; }  
        public int DescriptionFlags { get; set; } 
        public string ToolTip1 { get; set; }
        public string ToolTip2 { get; set; } 
        public string ToolTip3 { get; set; } 
        public string ToolTip4 { get; set; } 
        public string ToolTip5 { get; set; } 
        public string ToolTip6 { get; set; } 
        public string ToolTip7 { get; set; } 
        public string ToolTip8 { get; set; } 
        public int ToolTipFlags { get; set; } 
        public int ManaCostPercentage { get; set; } 
        public int StartRecoveryCategory { get; set; } 
        public int StartRecoveryTime { get; set; } 
        public int MaxTargetLevel { get; set; } 
        public int SpellFamilyName { get; set; } 
        public int SpellFamilyFlags1 { get; set; } 
        public int SpellFamilyFlags2 { get; set; } 
        public int MaxAffectedTargets { get; set; } 
        public int DmgClass { get; set; } 
        public int PreventionType { get; set; } 
        public int StanceBarOrder { get; set; } 
        public float DmgMultiplier1 { get; set; } 
        public float DmgMultiplier2 { get; set; } 
        public float DmgMultiplier3 { get; set; } 
        public int MinFactionId { get; set; } 
        public int MinReputation { get; set; } 
        public int RequiredAuraVision { get; set; }
    }
}
