//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_movement_template
    {
        public int entry { get; set; }
        public int point { get; set; }
        public float position_x { get; set; }
        public float position_y { get; set; }
        public float position_z { get; set; }
        public long waittime { get; set; }
        public int script_id { get; set; }
        public int textid1 { get; set; }
        public int textid2 { get; set; }
        public int textid3 { get; set; }
        public int textid4 { get; set; }
        public int textid5 { get; set; }
        public int emote { get; set; }
        public int spell { get; set; }
        public int wpguid { get; set; }
        public float orientation { get; set; }
        public int model1 { get; set; }
        public int model2 { get; set; }
    }
}
