//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template_classlevelstats
    {
        public sbyte Level { get; set; }
        public sbyte Class { get; set; }
        public int BaseHealthExp0 { get; set; }
        public int BaseMana { get; set; }
        public float BaseDamageExp0 { get; set; }
        public float BaseMeleeAttackPower { get; set; }
        public float BaseRangedAttackPower { get; set; }
        public int BaseArmor { get; set; }
    }
}
