//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_model_info
    {
        public int modelid { get; set; }
        public float bounding_radius { get; set; }
        public float combat_reach { get; set; }
        public byte gender { get; set; }
        public int modelid_other_gender { get; set; }
        public int modelid_other_team { get; set; }
    }
}
