//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_onkill_reputation
    {
        public int creature_id { get; set; }
        public short RewOnKillRepFaction1 { get; set; }
        public short RewOnKillRepFaction2 { get; set; }
        public short MaxStanding1 { get; set; }
        public short IsTeamAward1 { get; set; }
        public int RewOnKillRepValue1 { get; set; }
        public short MaxStanding2 { get; set; }
        public short IsTeamAward2 { get; set; }
        public int RewOnKillRepValue2 { get; set; }
        public byte TeamDependent { get; set; }
    }
}
