//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature
    {
        public long guid { get; set; }
        public int id { get; set; }
        public int map { get; set; }
        public int modelid { get; set; }
        public int equipment_id { get; set; }
        public float position_x { get; set; }
        public float position_y { get; set; }
        public float position_z { get; set; }
        public float orientation { get; set; }
        public long spawntimesecs { get; set; }
        public float spawndist { get; set; }
        public int currentwaypoint { get; set; }
        public long curhealth { get; set; }
        public long curmana { get; set; }
        public byte DeathState { get; set; }
        public byte MovementType { get; set; }
    }
}
