//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_ai_texts
    {
        public int entry { get; set; }
        public string content_default { get; set; }
        public string content_loc1 { get; set; }
        public string content_loc2 { get; set; }
        public string content_loc3 { get; set; }
        public string content_loc4 { get; set; }
        public string content_loc5 { get; set; }
        public string content_loc6 { get; set; }
        public string content_loc7 { get; set; }
        public string content_loc8 { get; set; }
        public int sound { get; set; }
        public byte type { get; set; }
        public byte language { get; set; }
        public int emote { get; set; }
        public string comment { get; set; }
    }
}
