//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_equip_template
    {
        public int entry { get; set; }
        public int equipentry1 { get; set; }
        public int equipentry2 { get; set; }
        public int equipentry3 { get; set; }
    }
}
