//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_ai_scripts
    {
        public long id { get; set; }
        public long creature_id { get; set; }
        public byte event_type { get; set; }
        public int event_inverse_phase_mask { get; set; }
        public long event_chance { get; set; }
        public long event_flags { get; set; }
        public int event_param1 { get; set; }
        public int event_param2 { get; set; }
        public int event_param3 { get; set; }
        public int event_param4 { get; set; }
        public byte action1_type { get; set; }
        public int action1_param1 { get; set; }
        public int action1_param2 { get; set; }
        public int action1_param3 { get; set; }
        public byte action2_type { get; set; }
        public int action2_param1 { get; set; }
        public int action2_param2 { get; set; }
        public int action2_param3 { get; set; }
        public byte action3_type { get; set; }
        public int action3_param1 { get; set; }
        public int action3_param2 { get; set; }
        public int action3_param3 { get; set; }
        public string comment { get; set; }
    }
}
