//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_equip_template_raw
    {
        public int entry { get; set; }
        public int equipmodel1 { get; set; }
        public int equipmodel2 { get; set; }
        public int equipmodel3 { get; set; }
        public long equipinfo1 { get; set; }
        public long equipinfo2 { get; set; }
        public long equipinfo3 { get; set; }
        public int equipslot1 { get; set; }
        public int equipslot2 { get; set; }
        public int equipslot3 { get; set; }
    }
}
