//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template_addon
    {
        public int entry { get; set; }
        public int mount { get; set; }
        public long bytes1 { get; set; }
        public byte b2_0_sheath { get; set; }
        public byte b2_1_flags { get; set; }
        public int emote { get; set; }
        public long moveflags { get; set; }
        public string auras { get; set; }
    }
}
