//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template
    {
        public int entry { get; set; }
        public long KillCredit1 { get; set; }
        public long KillCredit2 { get; set; }
        public int modelid_1 { get; set; }
        public int modelid_2 { get; set; }
        public string name { get; set; }
        public string subname { get; set; }
        public int gossip_menu_id { get; set; }
        public byte minlevel { get; set; }
        public byte maxlevel { get; set; }
        public long minhealth { get; set; }
        public long maxhealth { get; set; }
        public long minmana { get; set; }
        public long maxmana { get; set; }
        public int armor { get; set; }
        public int faction_A { get; set; }
        public int faction_H { get; set; }
        public long npcflag { get; set; }
        public float speed_walk { get; set; }
        public float speed_run { get; set; }
        public float scale { get; set; }
        public byte rank { get; set; }
        public float mindmg { get; set; }
        public float maxdmg { get; set; }
        public short dmgschool { get; set; }
        public long attackpower { get; set; }
        public float dmg_multiplier { get; set; }
        public long baseattacktime { get; set; }
        public long rangeattacktime { get; set; }
        public byte unit_class { get; set; }
        public long unit_flags { get; set; }
        public long dynamicflags { get; set; }
        public short family { get; set; }
        public short trainer_type { get; set; }
        public int trainer_spell { get; set; }
        public byte trainer_class { get; set; }
        public byte trainer_race { get; set; }
        public float minrangedmg { get; set; }
        public float maxrangedmg { get; set; }
        public int rangedattackpower { get; set; }
        public byte type { get; set; }
        public long type_flags { get; set; }
        public int lootid { get; set; }
        public int pickpocketloot { get; set; }
        public int skinloot { get; set; }
        public short resistance1 { get; set; }
        public short resistance2 { get; set; }
        public short resistance3 { get; set; }
        public short resistance4 { get; set; }
        public short resistance5 { get; set; }
        public short resistance6 { get; set; }
        public int PetSpellDataId { get; set; }
        public int mingold { get; set; }
        public int maxgold { get; set; }
        public string AIName { get; set; }
        public Nullable<byte> MovementType { get; set; }
        public byte InhabitType { get; set; }
        public byte Civilian { get; set; }
        public byte RacialLeader { get; set; }
        public byte RegenHealth { get; set; }
        public int equipment_id { get; set; }
        public int trainer_id { get; set; }
        public int vendor_id { get; set; }
        public long mechanic_immune_mask { get; set; }
        public long flags_extra { get; set; }
        public string ScriptName { get; set; }
    }
}
