//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_event_mail
    {
        public short @event { get; set; }
        public int raceMask { get; set; }
        public int quest { get; set; }
        public int mailTemplateId { get; set; }
        public int senderEntry { get; set; }
    }
}
