//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobject
    {
        public long guid { get; set; }
        public int id { get; set; }
        public int map { get; set; }
        public float position_x { get; set; }
        public float position_y { get; set; }
        public float position_z { get; set; }
        public float orientation { get; set; }
        public float rotation0 { get; set; }
        public float rotation1 { get; set; }
        public float rotation2 { get; set; }
        public float rotation3 { get; set; }
        public int spawntimesecs { get; set; }
        public byte animprogress { get; set; }
        public byte state { get; set; }
    }
}
