//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobject_loot_template
    {
        public int entry { get; set; }
        public int item { get; set; }
        public float ChanceOrQuestChance { get; set; }
        public byte groupid { get; set; }
        public int mincountOrRef { get; set; }
        public byte maxcount { get; set; }
        public int condition_id { get; set; }
    }
}
