//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_weather
    {
        public int zone { get; set; }
        public byte spring_rain_chance { get; set; }
        public byte spring_snow_chance { get; set; }
        public byte spring_storm_chance { get; set; }
        public byte summer_rain_chance { get; set; }
        public byte summer_snow_chance { get; set; }
        public byte summer_storm_chance { get; set; }
        public byte fall_rain_chance { get; set; }
        public byte fall_snow_chance { get; set; }
        public byte fall_storm_chance { get; set; }
        public byte winter_rain_chance { get; set; }
        public byte winter_snow_chance { get; set; }
        public byte winter_storm_chance { get; set; }
    }
}
