//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class gossip_menu
    {
        public int entry { get; set; }
        public int text_id { get; set; }
        public int script_id { get; set; }
        public int condition_id { get; set; }
    }
}
