//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class gossip_menu_option
    {
        public int menu_id { get; set; }
        public int id { get; set; }
        public int option_icon { get; set; }
        public string option_text { get; set; }
        public byte option_id { get; set; }
        public long npc_option_npcflag { get; set; }
        public int action_menu_id { get; set; }
        public int action_poi_id { get; set; }
        public int action_script_id { get; set; }
        public byte box_coded { get; set; }
        public long box_money { get; set; }
        public string box_text { get; set; }
        public int condition_id { get; set; }
    }
}
