//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class instance_template
    {
        public int map { get; set; }
        public int parent { get; set; }
        public byte levelMin { get; set; }
        public byte levelMax { get; set; }
        public byte maxPlayers { get; set; }
        public long reset_delay { get; set; }
        public int ghostEntranceMap { get; set; }
        public float ghostEntranceX { get; set; }
        public float ghostEntranceY { get; set; }
        public string ScriptName { get; set; }
    }
}
