//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class locales_page_text
    {
        public int entry { get; set; }
        public string Text_loc1 { get; set; }
        public string Text_loc2 { get; set; }
        public string Text_loc3 { get; set; }
        public string Text_loc4 { get; set; }
        public string Text_loc5 { get; set; }
        public string Text_loc6 { get; set; }
        public string Text_loc7 { get; set; }
        public string Text_loc8 { get; set; }
    }
}
