//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class locales_npc_text
    {
        public int entry { get; set; }
        public string Text0_0_loc1 { get; set; }
        public string Text0_0_loc2 { get; set; }
        public string Text0_0_loc3 { get; set; }
        public string Text0_0_loc4 { get; set; }
        public string Text0_0_loc5 { get; set; }
        public string Text0_0_loc6 { get; set; }
        public string Text0_0_loc7 { get; set; }
        public string Text0_0_loc8 { get; set; }
        public string Text0_1_loc1 { get; set; }
        public string Text0_1_loc2 { get; set; }
        public string Text0_1_loc3 { get; set; }
        public string Text0_1_loc4 { get; set; }
        public string Text0_1_loc5 { get; set; }
        public string Text0_1_loc6 { get; set; }
        public string Text0_1_loc7 { get; set; }
        public string Text0_1_loc8 { get; set; }
        public string Text1_0_loc1 { get; set; }
        public string Text1_0_loc2 { get; set; }
        public string Text1_0_loc3 { get; set; }
        public string Text1_0_loc4 { get; set; }
        public string Text1_0_loc5 { get; set; }
        public string Text1_0_loc6 { get; set; }
        public string Text1_0_loc7 { get; set; }
        public string Text1_0_loc8 { get; set; }
        public string Text1_1_loc1 { get; set; }
        public string Text1_1_loc2 { get; set; }
        public string Text1_1_loc3 { get; set; }
        public string Text1_1_loc4 { get; set; }
        public string Text1_1_loc5 { get; set; }
        public string Text1_1_loc6 { get; set; }
        public string Text1_1_loc7 { get; set; }
        public string Text1_1_loc8 { get; set; }
        public string Text2_0_loc1 { get; set; }
        public string Text2_0_loc2 { get; set; }
        public string Text2_0_loc3 { get; set; }
        public string Text2_0_loc4 { get; set; }
        public string Text2_0_loc5 { get; set; }
        public string Text2_0_loc6 { get; set; }
        public string Text2_0_loc7 { get; set; }
        public string Text2_0_loc8 { get; set; }
        public string Text2_1_loc1 { get; set; }
        public string Text2_1_loc2 { get; set; }
        public string Text2_1_loc3 { get; set; }
        public string Text2_1_loc4 { get; set; }
        public string Text2_1_loc5 { get; set; }
        public string Text2_1_loc6 { get; set; }
        public string Text2_1_loc7 { get; set; }
        public string Text2_1_loc8 { get; set; }
        public string Text3_0_loc1 { get; set; }
        public string Text3_0_loc2 { get; set; }
        public string Text3_0_loc3 { get; set; }
        public string Text3_0_loc4 { get; set; }
        public string Text3_0_loc5 { get; set; }
        public string Text3_0_loc6 { get; set; }
        public string Text3_0_loc7 { get; set; }
        public string Text3_0_loc8 { get; set; }
        public string Text3_1_loc1 { get; set; }
        public string Text3_1_loc2 { get; set; }
        public string Text3_1_loc3 { get; set; }
        public string Text3_1_loc4 { get; set; }
        public string Text3_1_loc5 { get; set; }
        public string Text3_1_loc6 { get; set; }
        public string Text3_1_loc7 { get; set; }
        public string Text3_1_loc8 { get; set; }
        public string Text4_0_loc1 { get; set; }
        public string Text4_0_loc2 { get; set; }
        public string Text4_0_loc3 { get; set; }
        public string Text4_0_loc4 { get; set; }
        public string Text4_0_loc5 { get; set; }
        public string Text4_0_loc6 { get; set; }
        public string Text4_0_loc7 { get; set; }
        public string Text4_0_loc8 { get; set; }
        public string Text4_1_loc1 { get; set; }
        public string Text4_1_loc2 { get; set; }
        public string Text4_1_loc3 { get; set; }
        public string Text4_1_loc4 { get; set; }
        public string Text4_1_loc5 { get; set; }
        public string Text4_1_loc6 { get; set; }
        public string Text4_1_loc7 { get; set; }
        public string Text4_1_loc8 { get; set; }
        public string Text5_0_loc1 { get; set; }
        public string Text5_0_loc2 { get; set; }
        public string Text5_0_loc3 { get; set; }
        public string Text5_0_loc4 { get; set; }
        public string Text5_0_loc5 { get; set; }
        public string Text5_0_loc6 { get; set; }
        public string Text5_0_loc7 { get; set; }
        public string Text5_0_loc8 { get; set; }
        public string Text5_1_loc1 { get; set; }
        public string Text5_1_loc2 { get; set; }
        public string Text5_1_loc3 { get; set; }
        public string Text5_1_loc4 { get; set; }
        public string Text5_1_loc5 { get; set; }
        public string Text5_1_loc6 { get; set; }
        public string Text5_1_loc7 { get; set; }
        public string Text5_1_loc8 { get; set; }
        public string Text6_0_loc1 { get; set; }
        public string Text6_0_loc2 { get; set; }
        public string Text6_0_loc3 { get; set; }
        public string Text6_0_loc4 { get; set; }
        public string Text6_0_loc5 { get; set; }
        public string Text6_0_loc6 { get; set; }
        public string Text6_0_loc7 { get; set; }
        public string Text6_0_loc8 { get; set; }
        public string Text6_1_loc1 { get; set; }
        public string Text6_1_loc2 { get; set; }
        public string Text6_1_loc3 { get; set; }
        public string Text6_1_loc4 { get; set; }
        public string Text6_1_loc5 { get; set; }
        public string Text6_1_loc6 { get; set; }
        public string Text6_1_loc7 { get; set; }
        public string Text6_1_loc8 { get; set; }
        public string Text7_0_loc1 { get; set; }
        public string Text7_0_loc2 { get; set; }
        public string Text7_0_loc3 { get; set; }
        public string Text7_0_loc4 { get; set; }
        public string Text7_0_loc5 { get; set; }
        public string Text7_0_loc6 { get; set; }
        public string Text7_0_loc7 { get; set; }
        public string Text7_0_loc8 { get; set; }
        public string Text7_1_loc1 { get; set; }
        public string Text7_1_loc2 { get; set; }
        public string Text7_1_loc3 { get; set; }
        public string Text7_1_loc4 { get; set; }
        public string Text7_1_loc5 { get; set; }
        public string Text7_1_loc6 { get; set; }
        public string Text7_1_loc7 { get; set; }
        public string Text7_1_loc8 { get; set; }
    }
}
