//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class locales_quest
    {
        public int entry { get; set; }
        public string Title_loc1 { get; set; }
        public string Title_loc2 { get; set; }
        public string Title_loc3 { get; set; }
        public string Title_loc4 { get; set; }
        public string Title_loc5 { get; set; }
        public string Title_loc6 { get; set; }
        public string Title_loc7 { get; set; }
        public string Title_loc8 { get; set; }
        public string Details_loc1 { get; set; }
        public string Details_loc2 { get; set; }
        public string Details_loc3 { get; set; }
        public string Details_loc4 { get; set; }
        public string Details_loc5 { get; set; }
        public string Details_loc6 { get; set; }
        public string Details_loc7 { get; set; }
        public string Details_loc8 { get; set; }
        public string Objectives_loc1 { get; set; }
        public string Objectives_loc2 { get; set; }
        public string Objectives_loc3 { get; set; }
        public string Objectives_loc4 { get; set; }
        public string Objectives_loc5 { get; set; }
        public string Objectives_loc6 { get; set; }
        public string Objectives_loc7 { get; set; }
        public string Objectives_loc8 { get; set; }
        public string OfferRewardText_loc1 { get; set; }
        public string OfferRewardText_loc2 { get; set; }
        public string OfferRewardText_loc3 { get; set; }
        public string OfferRewardText_loc4 { get; set; }
        public string OfferRewardText_loc5 { get; set; }
        public string OfferRewardText_loc6 { get; set; }
        public string OfferRewardText_loc7 { get; set; }
        public string OfferRewardText_loc8 { get; set; }
        public string RequestItemsText_loc1 { get; set; }
        public string RequestItemsText_loc2 { get; set; }
        public string RequestItemsText_loc3 { get; set; }
        public string RequestItemsText_loc4 { get; set; }
        public string RequestItemsText_loc5 { get; set; }
        public string RequestItemsText_loc6 { get; set; }
        public string RequestItemsText_loc7 { get; set; }
        public string RequestItemsText_loc8 { get; set; }
        public string EndText_loc1 { get; set; }
        public string EndText_loc2 { get; set; }
        public string EndText_loc3 { get; set; }
        public string EndText_loc4 { get; set; }
        public string EndText_loc5 { get; set; }
        public string EndText_loc6 { get; set; }
        public string EndText_loc7 { get; set; }
        public string EndText_loc8 { get; set; }
        public string ObjectiveText1_loc1 { get; set; }
        public string ObjectiveText1_loc2 { get; set; }
        public string ObjectiveText1_loc3 { get; set; }
        public string ObjectiveText1_loc4 { get; set; }
        public string ObjectiveText1_loc5 { get; set; }
        public string ObjectiveText1_loc6 { get; set; }
        public string ObjectiveText1_loc7 { get; set; }
        public string ObjectiveText1_loc8 { get; set; }
        public string ObjectiveText2_loc1 { get; set; }
        public string ObjectiveText2_loc2 { get; set; }
        public string ObjectiveText2_loc3 { get; set; }
        public string ObjectiveText2_loc4 { get; set; }
        public string ObjectiveText2_loc5 { get; set; }
        public string ObjectiveText2_loc6 { get; set; }
        public string ObjectiveText2_loc7 { get; set; }
        public string ObjectiveText2_loc8 { get; set; }
        public string ObjectiveText3_loc1 { get; set; }
        public string ObjectiveText3_loc2 { get; set; }
        public string ObjectiveText3_loc3 { get; set; }
        public string ObjectiveText3_loc4 { get; set; }
        public string ObjectiveText3_loc5 { get; set; }
        public string ObjectiveText3_loc6 { get; set; }
        public string ObjectiveText3_loc7 { get; set; }
        public string ObjectiveText3_loc8 { get; set; }
        public string ObjectiveText4_loc1 { get; set; }
        public string ObjectiveText4_loc2 { get; set; }
        public string ObjectiveText4_loc3 { get; set; }
        public string ObjectiveText4_loc4 { get; set; }
        public string ObjectiveText4_loc5 { get; set; }
        public string ObjectiveText4_loc6 { get; set; }
        public string ObjectiveText4_loc7 { get; set; }
        public string ObjectiveText4_loc8 { get; set; }
    }
}
