//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class locales_gossip_menu_option
    {
        public int menu_id { get; set; }
        public int id { get; set; }
        public string option_text_loc1 { get; set; }
        public string option_text_loc2 { get; set; }
        public string option_text_loc3 { get; set; }
        public string option_text_loc4 { get; set; }
        public string option_text_loc5 { get; set; }
        public string option_text_loc6 { get; set; }
        public string option_text_loc7 { get; set; }
        public string option_text_loc8 { get; set; }
        public string box_text_loc1 { get; set; }
        public string box_text_loc2 { get; set; }
        public string box_text_loc3 { get; set; }
        public string box_text_loc4 { get; set; }
        public string box_text_loc5 { get; set; }
        public string box_text_loc6 { get; set; }
        public string box_text_loc7 { get; set; }
        public string box_text_loc8 { get; set; }
    }
}
