//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class locales_points_of_interest
    {
        public int entry { get; set; }
        public string icon_name_loc1 { get; set; }
        public string icon_name_loc2 { get; set; }
        public string icon_name_loc3 { get; set; }
        public string icon_name_loc4 { get; set; }
        public string icon_name_loc5 { get; set; }
        public string icon_name_loc6 { get; set; }
        public string icon_name_loc7 { get; set; }
        public string icon_name_loc8 { get; set; }
    }
}
