//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_trainer_template
    {
        public int entry { get; set; }
        public int spell { get; set; }
        public long spellcost { get; set; }
        public int reqskill { get; set; }
        public int reqskillvalue { get; set; }
        public byte reqlevel { get; set; }
    }
}
