//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_text
    {
        public int ID { get; set; }
        public string text0_0 { get; set; }
        public string text0_1 { get; set; }
        public byte lang0 { get; set; }
        public float prob0 { get; set; }
        public int em0_0 { get; set; }
        public int em0_1 { get; set; }
        public int em0_2 { get; set; }
        public int em0_3 { get; set; }
        public int em0_4 { get; set; }
        public int em0_5 { get; set; }
        public string text1_0 { get; set; }
        public string text1_1 { get; set; }
        public byte lang1 { get; set; }
        public float prob1 { get; set; }
        public int em1_0 { get; set; }
        public int em1_1 { get; set; }
        public int em1_2 { get; set; }
        public int em1_3 { get; set; }
        public int em1_4 { get; set; }
        public int em1_5 { get; set; }
        public string text2_0 { get; set; }
        public string text2_1 { get; set; }
        public byte lang2 { get; set; }
        public float prob2 { get; set; }
        public int em2_0 { get; set; }
        public int em2_1 { get; set; }
        public int em2_2 { get; set; }
        public int em2_3 { get; set; }
        public int em2_4 { get; set; }
        public int em2_5 { get; set; }
        public string text3_0 { get; set; }
        public string text3_1 { get; set; }
        public byte lang3 { get; set; }
        public float prob3 { get; set; }
        public int em3_0 { get; set; }
        public int em3_1 { get; set; }
        public int em3_2 { get; set; }
        public int em3_3 { get; set; }
        public int em3_4 { get; set; }
        public int em3_5 { get; set; }
        public string text4_0 { get; set; }
        public string text4_1 { get; set; }
        public byte lang4 { get; set; }
        public float prob4 { get; set; }
        public int em4_0 { get; set; }
        public int em4_1 { get; set; }
        public int em4_2 { get; set; }
        public int em4_3 { get; set; }
        public int em4_4 { get; set; }
        public int em4_5 { get; set; }
        public string text5_0 { get; set; }
        public string text5_1 { get; set; }
        public byte lang5 { get; set; }
        public float prob5 { get; set; }
        public int em5_0 { get; set; }
        public int em5_1 { get; set; }
        public int em5_2 { get; set; }
        public int em5_3 { get; set; }
        public int em5_4 { get; set; }
        public int em5_5 { get; set; }
        public string text6_0 { get; set; }
        public string text6_1 { get; set; }
        public byte lang6 { get; set; }
        public float prob6 { get; set; }
        public int em6_0 { get; set; }
        public int em6_1 { get; set; }
        public int em6_2 { get; set; }
        public int em6_3 { get; set; }
        public int em6_4 { get; set; }
        public int em6_5 { get; set; }
        public string text7_0 { get; set; }
        public string text7_1 { get; set; }
        public byte lang7 { get; set; }
        public float prob7 { get; set; }
        public int em7_0 { get; set; }
        public int em7_1 { get; set; }
        public int em7_2 { get; set; }
        public int em7_3 { get; set; }
        public int em7_4 { get; set; }
        public int em7_5 { get; set; }
    }
}
