//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet_levelstats
    {
        public int creature_entry { get; set; }
        public byte level { get; set; }
        public int hp { get; set; }
        public int mana { get; set; }
        public long armor { get; set; }
        public int str { get; set; }
        public int agi { get; set; }
        public int sta { get; set; }
        public int inte { get; set; }
        public int spi { get; set; }
    }
}
