//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_classlevelstats
    {
        public byte @class { get; set; }
        public byte level { get; set; }
        public int basehp { get; set; }
        public int basemana { get; set; }
    }
}
