//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class playercreateinfo_action
    {
        public byte race { get; set; }
        public byte @class { get; set; }
        public int button { get; set; }
        public long action { get; set; }
        public int type { get; set; }
    }
}
