//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class points_of_interest
    {
        public int entry { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public int icon { get; set; }
        public int flags { get; set; }
        public int data { get; set; }
        public string icon_name { get; set; }
    }
}
