//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class reputation_spillover_template
    {
        public int faction { get; set; }
        public int faction1 { get; set; }
        public float rate_1 { get; set; }
        public byte rank_1 { get; set; }
        public int faction2 { get; set; }
        public float rate_2 { get; set; }
        public byte rank_2 { get; set; }
        public int faction3 { get; set; }
        public float rate_3 { get; set; }
        public byte rank_3 { get; set; }
        public int faction4 { get; set; }
        public float rate_4 { get; set; }
        public byte rank_4 { get; set; }
    }
}
