//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_bonus_data
    {
        public int entry { get; set; }
        public float direct_bonus { get; set; }
        public float dot_bonus { get; set; }
        public float ap_bonus { get; set; }
        public float ap_dot_bonus { get; set; }
        public string comments { get; set; }
    }
}
