//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_script_target
    {
        public int entry { get; set; }
        public byte type { get; set; }
        public int targetEntry { get; set; }
        public int inverseEffectMask { get; set; }
    }
}
