//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_chain
    {
        public int spell_id { get; set; }
        public int prev_spell { get; set; }
        public int first_spell { get; set; }
        public sbyte rank { get; set; }
        public int req_spell { get; set; }
    }
}
