//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_area
    {
        public int spell { get; set; }
        public int area { get; set; }
        public int quest_start { get; set; }
        public bool quest_start_active { get; set; }
        public int quest_end { get; set; }
        public int condition_id { get; set; }
        public int aura_spell { get; set; }
        public int racemask { get; set; }
        public bool gender { get; set; }
        public bool autocast { get; set; }
    }
}
