//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.World.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_threat
    {
        public int entry { get; set; }
        public short Threat { get; set; }
        public float multiplier { get; set; }
        public float ap_bonus { get; set; }
    }
}
